import { store } from './store';
import { SPECIES } from './data';
import {fishAsset} from './fishAssets';
import {playSfx} from './audio';

const layer = document.querySelector<HTMLDivElement>('#fish-overlay')!;
const bubbleLayer = document.querySelector<HTMLDivElement>('.fx-bubbles')!;
const app = document.querySelector<HTMLElement>('#app')!;
const cinematic = document.querySelector<HTMLElement>('#evolution-cinematic')!;
type Mode='cruise'|'dash'|'rest'|'explore';
type Mood='happy'|'normal'|'hungry'|'grumpy'|'poor-water';
type Motion={el:HTMLButtonElement;fishId:string;species:string;x:number;y:number;tx:number;ty:number;vx:number;vy:number;dir:1|-1;mode:Mode;until:number;phase:number;mood?:Mood;nextEmotion?:number};
const motions=new Map<string,Motion>();

function moodFor(id:string):Mood{const f=store.state.fish.find(x=>x.id===id);if(!f)return'normal';if(store.state.water<45)return'poor-water';if(f.hunger<30)return'hungry';if(f.happiness<35)return'grumpy';if(f.hunger>70&&f.happiness>70&&store.state.water>70)return'happy';return'normal'}
function showEmotion(m:Motion,symbol:string){const box=m.el.getBoundingClientRect(),el=document.createElement('span');el.className='fish-emotion';el.textContent=symbol;el.style.left=`${box.left+box.width*.55}px`;el.style.top=`${box.top+8}px`;document.body.append(el);setTimeout(()=>el.remove(),1100)}

window.addEventListener('feed-effect',event=>{const detail=(event as CustomEvent<{fishId:string;food:string;origin:DOMRect}>).detail,m=motions.get(detail.fishId);if(!m)return;m.mode='rest';m.until=performance.now()+1500;const target=m.el.getBoundingClientRect(),origin=detail.origin,pellet=document.createElement('span'),reaction=document.createElement('span');pellet.className=`food-flight food-${detail.food}`;pellet.textContent=detail.food==='plankton'?'✦':detail.food==='berry'?'●':'★';pellet.style.setProperty('--from-x',`${origin.left+origin.width/2}px`);pellet.style.setProperty('--from-y',`${origin.top+origin.height/2}px`);pellet.style.setProperty('--to-x',`${target.left+target.width*.48}px`);pellet.style.setProperty('--to-y',`${target.top+target.height*.42}px`);reaction.className='feed-reaction';reaction.innerHTML='<b>もぐもぐ</b><i>♥</i><i>♥</i><i>♥</i>';reaction.style.left=`${target.left+target.width/2}px`;reaction.style.top=`${target.top}px`;document.body.append(pellet,reaction);m.el.classList.remove('fish-fed');setTimeout(()=>{void playSfx('eatMunch');pellet.classList.add('arrived');m.el.classList.add('fish-fed');reaction.classList.add('show');for(let i=0;i<8;i++){const sparkle=document.createElement('i');sparkle.className='feed-sparkle';sparkle.style.left=`${target.left+target.width*.48}px`;sparkle.style.top=`${target.top+target.height*.42}px`;sparkle.style.setProperty('--angle',`${i*45}deg`);document.body.append(sparkle);setTimeout(()=>sparkle.remove(),750)}},430);setTimeout(()=>{pellet.remove();reaction.remove();m.el.classList.remove('fish-fed')},1350)});

function nextTarget(m:Motion,now:number){m.mood=moodFor(m.fishId);const roll=Math.random(),rest=m.mood==='grumpy'?.58:m.mood==='poor-water'?.48:m.mood==='hungry'?.2:.14,dash=m.mood==='happy'?.25:.1;m.mode=roll<dash?'dash':roll<dash+rest?'rest':roll<.62?'explore':'cruise';m.until=now+(m.mode==='dash'?700:m.mode==='rest'?1700+Math.random()*2600:2200+Math.random()*3800);if(m.mode==='rest'){m.tx=m.x;m.ty=m.y;return}m.tx=m.mood==='grumpy'?(Math.random()>.5?8+Math.random()*12:74+Math.random()*12):10+Math.random()*76;m.ty=m.mood==='hungry'?56+Math.random()*16:m.mood==='grumpy'?58+Math.random()*13:22+Math.random()*48;m.dir=m.tx>=m.x?1:-1}

function createFish(fishId:string){const fish=store.state.fish.find(f=>f.id===fishId);if(!fish)return;const spec=SPECIES[fish.species];const el=document.createElement('button');el.className='swimmer';el.dataset.fishId=fish.id;el.setAttribute('aria-label',`${fish.name} ${spec.name}`);el.innerHTML=`<span class="fish-motion"><img src="${fishAsset(fish.species)}" alt=""></span><span class="fish-name">${fish.name} - ${spec.name}</span>`;let hideTimer:number|undefined;const showName=()=>{if(hideTimer)window.clearTimeout(hideTimer);el.classList.add('show-name')};const hideName=()=>{if(hideTimer)window.clearTimeout(hideTimer);hideTimer=window.setTimeout(()=>el.classList.remove('show-name'),1400)};el.addEventListener('pointerenter',showName);el.addEventListener('pointerleave',hideName);el.addEventListener('focus',showName);el.addEventListener('blur',hideName);el.onclick=()=>window.dispatchEvent(new CustomEvent('fishselect',{detail:fish.id}));layer.append(el);const m:Motion={el,fishId:fish.id,species:fish.species,x:fish.x*100,y:fish.y*100,tx:fish.x*100,ty:fish.y*100,vx:0,vy:0,dir:fish.dir,mode:'cruise',until:0,phase:Math.random()*Math.PI*2};nextTarget(m,performance.now());motions.set(fish.id,m)}

let evolutionBusy=false;
async function playEvolution(m:Motion,newSpecies:string,fishName:string){if(evolutionBusy){m.species=newSpecies;m.el.querySelector<HTMLImageElement>('img')!.src=`${fishAsset(newSpecies as keyof typeof SPECIES)}`;return}void playSfx('evolveStart');evolutionBusy=true;m.mode='rest';m.until=performance.now()+4000;app.style.setProperty('--focus-x',`${m.x}%`);app.style.setProperty('--focus-y',`${m.y}%`);cinematic.style.setProperty('--evo-x',`${m.x}%`);cinematic.style.setProperty('--evo-y',`${m.y}%`);cinematic.querySelector('p')!.textContent=`${fishName} 進化の予感…`;app.classList.add('evolution-focus');await new Promise(r=>setTimeout(r,1150));void playSfx('evolveComplete');m.species=newSpecies;m.el.querySelector<HTMLImageElement>('img')!.src=`${fishAsset(newSpecies as keyof typeof SPECIES)}`;m.el.classList.add('evolving');cinematic.querySelector('p')!.textContent=`${SPECIES[newSpecies as keyof typeof SPECIES].name} に進化！`;app.classList.add('evolution-reveal');await new Promise(r=>setTimeout(r,950));app.classList.remove('evolution-focus','evolution-reveal');m.el.classList.remove('evolving');await new Promise(r=>setTimeout(r,450));evolutionBusy=false}
function reconcileFish(){const live=new Set(store.state.fish.map(f=>f.id));for(const[id,m]of motions)if(!live.has(id)){m.el.remove();motions.delete(id)}for(const fish of store.state.fish){let m=motions.get(fish.id);if(!m){createFish(fish.id);continue}const spec=SPECIES[fish.species];m.mood=moodFor(fish.id);m.el.dataset.mood=m.mood;if(m.species!==fish.species&&!m.el.classList.contains('evolving'))void playEvolution(m,fish.species,fish.name);m.el.querySelector<HTMLElement>('.fish-name')!.textContent=`${fish.name} - ${spec.name}`;m.el.setAttribute('aria-label',`${fish.name} ${spec.name}`)}}

let last=performance.now();function animate(now:number){const dt=Math.min(34,now-last)/1000;last=now;const width=layer.clientWidth,height=layer.clientHeight;for(const m of motions.values()){if(now>m.until||Math.hypot(m.tx-m.x,m.ty-m.y)<2)nextTarget(m,now);const dx=m.tx-m.x,dy=m.ty-m.y,dist=Math.max(1,Math.hypot(dx,dy));const speed=m.mode==='dash'?18:m.mode==='rest'?0:m.mode==='explore'?5.5:3.6;m.vx+=(dx/dist*speed-m.vx)*Math.min(1,dt*2.5);m.vy+=(dy/dist*speed-m.vy)*Math.min(1,dt*2.5);m.x=Math.max(2,Math.min(98,m.x+m.vx*dt));m.y=Math.max(8,Math.min(84,m.y+m.vy*dt));if(Math.abs(m.vx)>.3)m.dir=m.vx>0?1:-1;const bob=Math.sin(now/520+m.phase)*(m.mode==='rest'?5:2.5),angle=Math.max(-8,Math.min(8,m.vy*1.1)),x=Math.max(6,Math.min(width-m.el.offsetWidth-6,width*m.x/100)),y=Math.max(6,Math.min(height-m.el.offsetHeight-6,height*m.y/100+bob));m.el.style.transform=`translate3d(${x}px,${y}px,0) rotate(${angle}deg)`;m.el.dataset.mode=m.mode;m.el.style.setProperty('--dir',String(m.dir));m.el.style.setProperty('--tail-speed',m.mode==='dash'?'.22s':m.mode==='rest'?'1.15s':'.55s')}requestAnimationFrame(animate)}

function buildBubbles(){bubbleLayer.innerHTML='';for(let i=0;i<42;i++){const b=document.createElement('i');const size=12+Math.random()*30;b.style.cssText=`--x:${3+Math.random()*94}%;--size:${size}px;--duration:${4+Math.random()*7}s;--delay:${-Math.random()*12}s;--drift:${-38+Math.random()*76}px`;bubbleLayer.append(b)}}

store.on(reconcileFish);reconcileFish();buildBubbles();requestAnimationFrame(animate);
