import type {Decoration,FoodId,GameState,SpeciesId} from './types';
const key='aqua-alter-save-v3';
const starter=():GameState=>({coins:120,pearls:1,water:88,cleanSpots:2,fish:[{id:crypto.randomUUID(),name:'ミオ',species:'medaka',x:.38,y:.46,dir:1,hunger:64,happiness:78,foods:[],bornAt:Date.now()},{id:crypto.randomUUID(),name:'ルル',species:'medaka',x:.62,y:.34,dir:-1,hunger:72,happiness:82,foods:['plankton'],bornAt:Date.now()}],decorations:[],inventory:{plankton:4,berry:2,stardust:1},discovered:['medaka'],lastTick:Date.now()});
export class Store{state:GameState;listeners=new Set<()=>void>();constructor(){try{this.state={...starter(),...JSON.parse(localStorage.getItem(key)||'null')};this.state.decorations=(this.state.decorations||[]).map(d=>({...d,scale:d.scale??1,rotation:d.rotation??0,flipped:d.flipped??false,z:d.z??1,placed:d.placed??true}))}catch{this.state=starter()}}
 on(fn:()=>void){this.listeners.add(fn);return()=>this.listeners.delete(fn)} emit(){this.state.lastTick=Date.now();localStorage.setItem(key,JSON.stringify(this.state));this.listeners.forEach(f=>f())}
 buyFood(id:FoodId,cost:number){if(this.state.coins<cost)return false;this.state.coins-=cost;this.state.inventory[id]++;this.emit();return true}
 addDecor(type:Decoration['type'],cost:number){if(this.state.coins<cost)return false;this.state.coins-=cost;const id=crypto.randomUUID();this.state.decorations.push({id,type,x:.5,y:.76,scale:1,rotation:0,flipped:false,z:this.state.decorations.length+1,placed:true});this.emit();window.dispatchEvent(new CustomEvent('decorselect',{detail:id}));return true}
 updateDecor(id:string,patch:Partial<Decoration>){const decor=this.state.decorations.find(d=>d.id===id);if(!decor)return;Object.assign(decor,patch);this.emit()}
 storeDecor(id:string){this.updateDecor(id,{placed:false})}
 placeDecor(id:string){const maxZ=Math.max(0,...this.state.decorations.map(d=>d.z));this.updateDecor(id,{placed:true,x:.5,y:.76,z:maxZ+1})}
 feed(fishId:string,food:FoodId){const f=this.state.fish.find(x=>x.id===fishId);if(!f||this.state.inventory[food]<1)return null;this.state.inventory[food]--;f.foods.push(food);f.hunger=Math.min(100,f.hunger+28);f.happiness=Math.min(100,f.happiness+7);const before=f.species;f.species=this.evolve(f.species,f.foods);if(!this.state.discovered.includes(f.species))this.state.discovered.push(f.species);this.emit();return before!==f.species?f.species:false}
 evolve(current:SpeciesId,foods:FoodId[]):SpeciesId{const plants=this.state.decorations.filter(d=>d.placed&&d.type==='plant').length, crystals=this.state.decorations.filter(d=>d.placed&&d.type==='crystal').length;if(current==='neon'&&foods.filter(x=>x==='stardust').length>=3&&this.state.water>=90&&crystals>=1)return'astral';if(new Set(foods).size>=3&&crystals>=1)return'neon';if(foods.filter(x=>x==='plankton').length>=3&&plants>=2)return'mossback';if(foods.filter(x=>x==='berry').length>=3)return'sunfin';return current}
 clean(){if(this.state.cleanSpots<1)return;this.state.cleanSpots--;this.state.coins+=12;this.state.water=Math.min(100,this.state.water+5);this.emit()}
 sell(id:string){const i=this.state.fish.findIndex(f=>f.id===id);if(i<0||this.state.fish.length===1)return false;const {SPECIES}=requireData();this.state.coins+=SPECIES[this.state.fish[i].species].value;this.state.fish.splice(i,1);this.emit();return true}
 buyFish(){if(this.state.coins<55||this.state.fish.length>=8)return false;this.state.coins-=55;this.state.fish.push({id:crypto.randomUUID(),name:['ナギ','ソラ','アオ','キラ'][this.state.fish.length%4],species:'medaka',x:.25+Math.random()*.5,y:.3+Math.random()*.35,dir:Math.random()>.5?1:-1,hunger:70,happiness:75,foods:[],bornAt:Date.now()});this.emit();return true}
 reward(food?:FoodId){if(food)this.state.inventory[food]++;else this.state.coins+=40;this.emit()}}
import {SPECIES as speciesData} from './data';function requireData(){return{SPECIES:speciesData}}
export const store=new Store();
