import type {BackgroundId,Decoration,FoodId,GameState,SpeciesId,SubstrateId} from './types';
const key='aqua-alter-save-v4';
const SAVE_VERSION=8,clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const FOOD_IDS:FoodId[]=['plankton','berry','stardust','protein','mineral'];
const SPECIES_IDS:SpeciesId[]=['medaka','sunfin','mossback','neon','solarcrown','grovewhale','astral','saplingback','greattreeleviathan','stonecalf','cragwhale','petalbloom','floralqueen'];
const BACKGROUND_IDS:BackgroundId[]=['fancy','fantasy','rocky','natural','river','lake'];
const WATER_DECAY_PER_MINUTE=.045,FISH_WATER_LOAD_PER_MINUTE=.008,MIN_DIRT_INTERVAL=40,MAX_DIRT_INTERVAL=60,MAX_FISH=8;
const dirtInterval=(fishCount:number)=>MAX_DIRT_INTERVAL-(clamp(fishCount,1,MAX_FISH)-1)*(MAX_DIRT_INTERVAL-MIN_DIRT_INTERVAL)/(MAX_FISH-1);
const starter=():GameState=>({schemaVersion:SAVE_VERSION,coins:120,pearls:1,water:88,cleanSpots:2,dirtProgressMinutes:0,fish:[{id:crypto.randomUUID(),name:'ミオ',species:'medaka',x:.38,y:.46,dir:1,hunger:64,happiness:78,foods:[],bornAt:Date.now()},{id:crypto.randomUUID(),name:'ルル',species:'medaka',x:.62,y:.34,dir:-1,hunger:72,happiness:82,foods:['plankton'],bornAt:Date.now()}],decorations:[],inventory:{plankton:4,berry:2,stardust:1,protein:1,mineral:1},discovered:['medaka'],substrate:'pastel',ownedSubstrates:['pastel'],background:'fancy',ownedBackgrounds:['fancy'],lastTick:Date.now()});
function migrate(raw:unknown):GameState{const base=starter(),data=raw&&typeof raw==='object'?raw as Partial<GameState>:{};const fish=Array.isArray(data.fish)?data.fish.filter(f=>f&&typeof f.id==='string').slice(0,8).map(f=>({...f,name:String(f.name||'ななし').trim().slice(0,12)||'ななし',x:clamp(Number(f.x)||.5,.02,.98),y:clamp(Number(f.y)||.5,.08,.9),hunger:clamp(Number(f.hunger)||8,8,100),happiness:clamp(Number(f.happiness)||12,12,100),foods:Array.isArray(f.foods)?f.foods.filter((x):x is FoodId=>FOOD_IDS.includes(x as FoodId)).slice(-40):[]})):base.fish;const background=BACKGROUND_IDS.includes(data.background as BackgroundId)?data.background as BackgroundId:'fancy',ownedBackgrounds:BackgroundId[]=Array.isArray(data.ownedBackgrounds)?data.ownedBackgrounds.filter((x):x is BackgroundId=>BACKGROUND_IDS.includes(x as BackgroundId)):['fancy'];if(!ownedBackgrounds.includes('fancy'))ownedBackgrounds.unshift('fancy');if(!ownedBackgrounds.includes(background))ownedBackgrounds.push(background);return{...base,...data,schemaVersion:SAVE_VERSION,coins:Math.max(0,Math.floor(Number(data.coins)||0)),pearls:Math.max(0,Math.floor(Number(data.pearls)||0)),water:clamp(Number(data.water)||20,20,100),cleanSpots:clamp(Math.floor(Number(data.cleanSpots)||0),0,6),dirtProgressMinutes:clamp(Number(data.dirtProgressMinutes)||0,0,MAX_DIRT_INTERVAL),fish:fish.length?fish:base.fish,decorations:Array.isArray(data.decorations)?data.decorations.slice(0,60).map(d=>({...d,scale:clamp(Number(d.scale)||1,.3,2.8),rotation:Number(d.rotation)||0,flipped:!!d.flipped,z:clamp(Number(d.z)||1,-20,20),placed:d.placed!==false})):[],inventory:{plankton:Math.max(0,Math.floor(Number(data.inventory?.plankton)||0)),berry:Math.max(0,Math.floor(Number(data.inventory?.berry)||0)),stardust:Math.max(0,Math.floor(Number(data.inventory?.stardust)||0)),protein:Math.max(0,Math.floor(Number(data.inventory?.protein)||0)),mineral:Math.max(0,Math.floor(Number(data.inventory?.mineral)||0))},discovered:Array.isArray(data.discovered)?data.discovered.filter((x):x is SpeciesId=>SPECIES_IDS.includes(x as SpeciesId)):['medaka'],background,ownedBackgrounds,lastTick:Number(data.lastTick)||Date.now()}}
export class Store{state:GameState;listeners=new Set<()=>void>();constructor(){const saved=localStorage.getItem(key);try{this.state=migrate(saved?JSON.parse(saved):null);localStorage.setItem(key,JSON.stringify(this.state))}catch{if(saved)localStorage.setItem(`${key}-corrupt-${Date.now()}`,saved);this.state=starter();localStorage.setItem(key,JSON.stringify(this.state))}}
 on(fn:()=>void){this.listeners.add(fn);return()=>this.listeners.delete(fn)} emit(){localStorage.setItem(key,JSON.stringify(this.state));this.listeners.forEach(f=>f())}
 advanceTime(now=Date.now()){const elapsed=Math.min(12*60*60*1000,Math.max(0,now-(this.state.lastTick||now))),minutes=elapsed/60000;if(minutes<.25)return;const fishLoad=Math.max(1,this.state.fish.length),plants=this.state.decorations.filter(d=>d.placed&&['plant','filter','light','vallisneria','treeBroadleaf','treeWeeping','plantBroadleafLarge','grassMeadowLarge'].includes(d.type)).length;this.state.water=Math.max(20,this.state.water-minutes*(WATER_DECAY_PER_MINUTE+FISH_WATER_LOAD_PER_MINUTE*fishLoad));for(const fish of this.state.fish){fish.hunger=Math.max(8,fish.hunger-minutes*.055);const environment=(this.state.water-55)/100+Math.min(.18,plants*.025);fish.happiness=Math.max(12,Math.min(100,fish.happiness+minutes*(environment*.018-(fish.hunger<30?.025:0))))}const interval=dirtInterval(fishLoad),progress=this.state.dirtProgressMinutes+minutes,spawned=Math.floor(progress/interval);this.state.dirtProgressMinutes=progress%interval;if(spawned>0)this.state.cleanSpots=Math.min(6,this.state.cleanSpots+spawned);this.state.lastTick=now;this.emit()}
 buyFood(id:FoodId,cost:number){if(this.state.coins<cost)return false;this.state.coins-=cost;this.state.inventory[id]++;this.emit();return true}
 buySubstrate(id:SubstrateId,cost:number){if(this.state.ownedSubstrates.includes(id)){this.state.substrate=id;this.emit();return true}if(this.state.coins<cost)return false;this.state.coins-=cost;this.state.ownedSubstrates.push(id);this.state.substrate=id;this.emit();return true}
 buyBackground(id:BackgroundId,cost:number){if(this.state.ownedBackgrounds.includes(id)){this.state.background=id;this.emit();return true}if(this.state.coins<cost)return false;this.state.coins-=cost;this.state.ownedBackgrounds.push(id);this.state.background=id;this.emit();return true}
 addDecor(type:Decoration['type'],cost:number){if(this.state.coins<cost)return false;this.state.coins-=cost;const id=crypto.randomUUID();this.state.decorations.push({id,type,x:.5,y:.76,scale:1,rotation:0,flipped:false,z:this.state.decorations.length+1,placed:true});this.emit();window.dispatchEvent(new CustomEvent('decorselect',{detail:id}));return true}
 updateDecor(id:string,patch:Partial<Decoration>){const decor=this.state.decorations.find(d=>d.id===id);if(!decor)return;Object.assign(decor,patch);this.emit()}
 renameFish(id:string,name:string){const fish=this.state.fish.find(f=>f.id===id);const clean=name.trim().replace(/\s+/g,' ').slice(0,12);if(!fish||!clean)return false;fish.name=clean;this.emit();return true}
 storeDecor(id:string){this.updateDecor(id,{placed:false})}
 placeDecor(id:string){const maxZ=Math.max(0,...this.state.decorations.map(d=>d.z));this.updateDecor(id,{placed:true,x:.5,y:.76,z:maxZ+1})}
 feed(fishId:string,food:FoodId){const f=this.state.fish.find(x=>x.id===fishId);if(!f||this.state.inventory[food]<1)return null;this.state.inventory[food]--;f.foods.push(food);f.hunger=Math.min(100,f.hunger+28);f.happiness=Math.min(100,f.happiness+7);const before=f.species;f.species=this.evolve(f.species,f.foods);if(!this.state.discovered.includes(f.species))this.state.discovered.push(f.species);this.emit();return before!==f.species?f.species:false}
 evolve(current:SpeciesId,foods:FoodId[]):SpeciesId{
  const placed=this.state.decorations.filter(d=>d.placed),plants=placed.filter(d=>['plant','filter','light','vallisneria','treeBroadleaf','treeWeeping','plantBroadleafLarge','grassMeadowLarge'].includes(d.type)).length,trees=placed.filter(d=>['treeBroadleaf','treeWeeping'].includes(d.type)).length,rocks=placed.filter(d=>['stones','basalt','graniteLarge','slateLarge','sandstoneLarge'].includes(d.type)).length,blooms=placed.filter(d=>['coral','light','plantBroadleafLarge','grassMeadowLarge'].includes(d.type)).length,crystals=placed.filter(d=>d.type==='crystal').length,count=(food:FoodId)=>foods.filter(x=>x===food).length;
  if(current==='saplingback'&&count('plankton')>=5&&count('mineral')>=9&&plants>=6&&trees>=2&&this.state.water>=94)return'greattreeleviathan';
  if(current==='stonecalf'&&count('mineral')>=9&&count('protein')>=8&&rocks>=7&&this.state.water>=92)return'cragwhale';
  if(current==='petalbloom'&&count('berry')>=5&&count('stardust')>=10&&blooms>=6&&this.state.water>=97)return'floralqueen';
  if(current==='sunfin'&&count('protein')>=4)return'solarcrown';if(current==='mossback'&&count('mineral')>=4&&plants>=3)return'grovewhale';if(current==='neon'&&count('stardust')>=4&&this.state.water>=90&&crystals>=1)return'astral';if(current!=='medaka')return current;
  if(count('plankton')>=2&&count('mineral')>=5&&plants>=4&&trees>=1&&this.state.water>=90)return'saplingback';
  if(count('mineral')>=4&&count('protein')>=4&&rocks>=4&&this.state.water>=88)return'stonecalf';
  if(count('berry')>=2&&count('stardust')>=5&&blooms>=4&&this.state.water>=94)return'petalbloom';
  if(new Set(foods).size>=3&&crystals>=1)return'neon';if(count('plankton')>=3&&plants>=2)return'mossback';if(count('berry')>=3)return'sunfin';return current
 }
 clean(){if(this.state.cleanSpots<1)return;this.state.cleanSpots--;this.state.coins+=12;this.state.water=Math.min(100,this.state.water+12);this.emit()}
 grantCoins(amount:number){this.state.coins+=Math.max(0,Math.floor(amount));this.emit()}
 sell(id:string){const i=this.state.fish.findIndex(f=>f.id===id);if(i<0||this.state.fish.length===1)return false;const {SPECIES}=requireData();this.state.coins+=SPECIES[this.state.fish[i].species].value;this.state.fish.splice(i,1);this.emit();return true}
 buyFish(){if(this.state.coins<55||this.state.fish.length>=8)return false;this.state.coins-=55;this.state.fish.push({id:crypto.randomUUID(),name:['ナギ','ソラ','アオ','キラ'][this.state.fish.length%4],species:'medaka',x:.25+Math.random()*.5,y:.3+Math.random()*.35,dir:Math.random()>.5?1:-1,hunger:70,happiness:75,foods:[],bornAt:Date.now()});this.emit();return true}
 reward(food?:FoodId){if(food)this.state.inventory[food]++;else this.state.coins+=150;this.emit()}}
import {SPECIES as speciesData} from './data';function requireData(){return{SPECIES:speciesData}}
export const store=new Store();
store.advanceTime();
