import {FOODS,SHOP,SPECIES} from './data';import {store} from './store';import type {FoodId} from './types';
let selected=store.state.fish[0]?.id;let panel:'fish'|'shop'|'book'|null=null;const hud=document.querySelector('#hud')!;
const toast=(m:string)=>{const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),2400)};
const bar=(v:number)=>`<span class="meter"><i style="width:${v}%"></i></span>`;
function render(){const s=store.state,f=s.fish.find(x=>x.id===selected)||s.fish[0];hud.innerHTML=`<header><div class="brand"><b>AQUA</b><span>ALTER</span></div><div class="resources"><span>◉ ${s.coins}</span><span>◈ ${s.pearls}</span><span>水質 ${bar(s.water)} ${s.water}</span></div></header><nav><button data-tab="shop">◌<small>ショップ</small></button><button data-tab="book">◇<small>図鑑 ${s.discovered.length}/5</small></button><button data-clean ${s.cleanSpots?'':'disabled'}>✧<small>掃除 ${s.cleanSpots}</small></button><button data-ad>▶<small>ごほうび</small></button></nav><div class="hint">魚をタップして、お世話をしよう</div>${panel==='fish'&&f?fishPanel(f):panel==='shop'?shopPanel():panel==='book'?bookPanel():''}`;bind()}
function fishPanel(f:NonNullable<typeof store.state.fish[0]>){return`<section class="drawer"><button class="close">×</button><p class="eyebrow">SELECTED FISH</p><h2>${f.name}<small>${SPECIES[f.species].name}</small></h2><div class="stats"><label>おなか ${bar(f.hunger)}</label><label>ごきげん ${bar(f.happiness)}</label></div><p class="hintline">進化のヒント：${SPECIES[f.species].hint}</p><h3>餌をあげる</h3><div class="cards">${(Object.keys(FOODS)as FoodId[]).map(k=>`<button class="food" data-food="${k}" ${store.state.inventory[k]?'':'disabled'}><i style="--c:#${FOODS[k].color.toString(16)}">${FOODS[k].icon}</i><b>${FOODS[k].name}</b><span>所持 ${store.state.inventory[k]}</span></button>`).join('')}</div><p class="history">食べたもの：${f.foods.length?f.foods.map(x=>FOODS[x].icon).join('　'):'まだありません'}</p><button class="sell" ${store.state.fish.length===1?'disabled':''}>この魚を ${SPECIES[f.species].value}◉ で送り出す</button></section>`}
function shopPanel(){return`<section class="drawer"><button class="close">×</button><p class="eyebrow">AQUARIUM SHOP</p><h2>水辺商店<small>環境を整えて進化を導こう</small></h2><h3>餌</h3><div class="shopgrid">${(Object.keys(FOODS)as FoodId[]).map(k=>`<button data-buyfood="${k}"><b>${FOODS[k].icon} ${FOODS[k].name}</b><span>${FOODS[k].desc}</span><em>${FOODS[k].cost} ◉</em></button>`).join('')}</div><h3>水槽アイテム</h3><div class="shopgrid">${SHOP.map(x=>`<button data-decor="${x.type}"><b>${x.icon} ${x.name}</b><span>${x.desc}</span><em>${x.cost} ◉</em></button>`).join('')}</div><button class="primary" data-fish>稚魚を迎える · 55 ◉</button></section>`}
function bookPanel(){return`<section class="drawer"><button class="close">×</button><p class="eyebrow">AQUA ARCHIVE</p><h2>いきもの図鑑<small>進化を見つけて記録しよう</small></h2><div class="species">${(Object.keys(SPECIES)as(Array<keyof typeof SPECIES>)).map(k=>{const got=store.state.discovered.includes(k),x=SPECIES[k];return`<article class="${got?'':'locked'}"><i style="--fish:#${x.color.toString(16)}"></i><div><b>${got?x.name:'？？？？？'}</b><span>${got?x.hint:'まだ見つかっていません'}</span></div><em>${got?x.value+' ◉':'未発見'}</em></article>`}).join('')}</div></section>`}
function bind(){hud.querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.onclick=()=>{panel=b.dataset.tab as typeof panel;render()});hud.querySelector('.close')?.addEventListener('click',()=>{panel=null;render()});hud.querySelector('[data-clean]')?.addEventListener('click',()=>{store.clean();toast('水槽がきれいになった！ +12 ◉')});hud.querySelectorAll<HTMLElement>('[data-food]').forEach(b=>b.onclick=()=>{const evo=store.feed(selected!,b.dataset.food as FoodId);if(evo)toast(`進化！ ${SPECIES[evo].name} になった`)});hud.querySelector('.sell')?.addEventListener('click',()=>{if(selected&&store.sell(selected)){selected=store.state.fish[0]?.id;panel=null;toast('新しい飼い主へ送り出しました')}});hud.querySelectorAll<HTMLElement>('[data-buyfood]').forEach(b=>b.onclick=()=>{const k=b.dataset.buyfood as FoodId;store.buyFood(k,FOODS[k].cost)?toast(`${FOODS[k].name}を購入`):toast('コインが足りません')});hud.querySelectorAll<HTMLElement>('[data-decor]').forEach(b=>b.onclick=()=>{const x=SHOP.find(v=>v.type===b.dataset.decor)!;store.addDecor(x.type,x.cost)?toast(`${x.name}を設置しました`):toast('コインが足りません')});hud.querySelector('[data-fish]')?.addEventListener('click',()=>store.buyFish()?toast('新しい稚魚が仲間入り！'):toast('コイン不足、または水槽が満員です'));hud.querySelector('[data-ad]')?.addEventListener('click',()=>{const o=document.createElement('div');o.className='ad';o.innerHTML='<div><small>REWARD PREVIEW</small><b>水辺からの贈りもの</b><span>広告SDK接続前のデモです</span><button>受け取る · +40 ◉</button></div>';document.body.append(o);o.querySelector('button')!.onclick=()=>{store.reward();o.remove();toast('ごほうび +40 ◉')}})}
window.addEventListener('fishselect',(e)=>{selected=(e as CustomEvent).detail;panel='fish';render()});store.on(render);render();
